
server:
  port: 8083

#******** MongoDB CLoud Configuration

#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://puneetshrivastava:D0ovWjQ7OKeGo3uq@rating-ms-db.yu4v8kd.mongodb.net/?retryWrites=true&w=majority&appName=Rating-MS-DB
#      database: Rating-ms-db


spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rating-microservices

  config:
    import: configserver:http://localhost:8084

#  eureka:
#    instance:
#      prefer-ip-address: true
#      hostname: localhost
#      client:
#        fetch-registry: true
#        register-with-eureka: true
#        service-url:
#          defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-44442616.okta.com/oauth2/default
    audience: api://default